const messages = {
  de: { menu: "Menü", title: "Speisekarte", loading: "Speisekarte wird geladen …", unavailable: "Diese Speisekarte ist derzeit nicht verfügbar.", retry: "Erneut versuchen", error: "Die Speisekarte konnte nicht geladen werden.", draft: "Entwurf", upload: "JPEG oder PDF hochladen", order: "Reihenfolge speichern", previous: "Vorherige Seite", next: "Nächste Seite", zoomIn: "Vergrößern", zoomOut: "Verkleinern", page: "Seite", preview: "Vorschau", publish: "Fassung veröffentlichen", unpublish: "Veröffentlichung zurücknehmen", published: "Veröffentlicht", noEntitlement: "Der Katalog ist derzeit nicht freigeschaltet. Dein Entwurf bleibt erhalten.", ownerError: "Die Speisekarte konnte nicht gespeichert werden.", saved: "Entwurf gespeichert.", version: "Version", required: "Bitte zuerst mindestens eine Seite hochladen.", fileInvalid: "Nur JPEG oder PDF bis 10 MB pro Datei sind erlaubt." },
  en: { menu: "Menu", title: "Menu", loading: "Loading menu …", unavailable: "This menu is currently unavailable.", retry: "Try again", error: "The menu could not be loaded.", draft: "Draft", upload: "Upload JPEG or PDF", order: "Save order", previous: "Previous page", next: "Next page", zoomIn: "Zoom in", zoomOut: "Zoom out", page: "Page", preview: "Preview", publish: "Publish version", unpublish: "Unpublish", published: "Published", noEntitlement: "The catalog is not currently enabled. Your draft remains saved.", ownerError: "The menu could not be saved.", saved: "Draft saved.", version: "Version", required: "Upload at least one page first.", fileInvalid: "Only JPEG or PDF up to 10 MB per file is allowed." },
  fr: { menu: "Menu", title: "Carte", loading: "Chargement de la carte …", unavailable: "Cette carte est actuellement indisponible.", retry: "Réessayer", error: "Impossible de charger la carte.", draft: "Brouillon", upload: "Importer JPEG ou PDF", order: "Enregistrer l’ordre", previous: "Page précédente", next: "Page suivante", zoomIn: "Agrandir", zoomOut: "Réduire", page: "Page", preview: "Aperçu", publish: "Publier la version", unpublish: "Retirer la publication", published: "Publié", noEntitlement: "Le catalogue n’est pas activé. Votre brouillon est conservé.", ownerError: "Impossible d’enregistrer la carte.", saved: "Brouillon enregistré.", version: "Version", required: "Importez au moins une page.", fileInvalid: "Seuls JPEG ou PDF jusqu’à 10 Mo sont autorisés." },
  it: { menu: "Menù", title: "Menù", loading: "Caricamento del menù …", unavailable: "Questo menù non è disponibile.", retry: "Riprova", error: "Impossibile caricare il menù.", draft: "Bozza", upload: "Carica JPEG o PDF", order: "Salva l’ordine", previous: "Pagina precedente", next: "Pagina successiva", zoomIn: "Ingrandisci", zoomOut: "Riduci", page: "Pagina", preview: "Anteprima", publish: "Pubblica versione", unpublish: "Ritira pubblicazione", published: "Pubblicato", noEntitlement: "Il catalogo non è attivo. La bozza resta salvata.", ownerError: "Impossibile salvare il menù.", saved: "Bozza salvata.", version: "Versione", required: "Carica almeno una pagina.", fileInvalid: "Sono ammessi solo JPEG o PDF fino a 10 MB." },
  es: { menu: "Menú", title: "Menú", loading: "Cargando menú …", unavailable: "Este menú no está disponible.", retry: "Reintentar", error: "No se pudo cargar el menú.", draft: "Borrador", upload: "Subir JPEG o PDF", order: "Guardar orden", previous: "Página anterior", next: "Página siguiente", zoomIn: "Ampliar", zoomOut: "Reducir", page: "Página", preview: "Vista previa", publish: "Publicar versión", unpublish: "Retirar publicación", published: "Publicado", noEntitlement: "El catálogo no está habilitado. Tu borrador se conserva.", ownerError: "No se pudo guardar el menú.", saved: "Borrador guardado.", version: "Versión", required: "Sube al menos una página.", fileInvalid: "Solo JPEG o PDF de hasta 10 MB por archivo." },
  zh: { menu: "菜单", title: "菜单", loading: "正在加载菜单…", unavailable: "此菜单目前不可用。", retry: "重试", error: "无法加载菜单。", draft: "草稿", upload: "上传 JPEG 或 PDF", order: "保存顺序", previous: "上一页", next: "下一页", zoomIn: "放大", zoomOut: "缩小", page: "页", preview: "预览", publish: "发布版本", unpublish: "取消发布", published: "已发布", noEntitlement: "当前未开通菜单功能，草稿将保留。", ownerError: "无法保存菜单。", saved: "草稿已保存。", version: "版本", required: "请先上传至少一页。", fileInvalid: "仅允许每个文件不超过 10 MB 的 JPEG 或 PDF。" },
  ko: { menu: "메뉴", title: "메뉴", loading: "메뉴를 불러오는 중…", unavailable: "현재 이 메뉴를 볼 수 없습니다.", retry: "다시 시도", error: "메뉴를 불러오지 못했습니다.", draft: "초안", upload: "JPEG 또는 PDF 업로드", order: "순서 저장", previous: "이전 페이지", next: "다음 페이지", zoomIn: "확대", zoomOut: "축소", page: "페이지", preview: "미리보기", publish: "버전 게시", unpublish: "게시 취소", published: "게시됨", noEntitlement: "메뉴 기능이 비활성화되어도 초안은 보존됩니다.", ownerError: "메뉴를 저장하지 못했습니다.", saved: "초안을 저장했습니다.", version: "버전", required: "먼저 한 페이지 이상 업로드하세요.", fileInvalid: "파일당 최대 10 MB의 JPEG 또는 PDF만 허용됩니다." },
} as const;

const representationMessages = {
  de: { overview: "Übersicht", originalCard: "Originalkarte", displayChoice: "Darstellung wählen", textDraft: "Eigene Textübersicht", saveText: "Textentwurf speichern", publishText: "Übersicht veröffentlichen", unpublishText: "Übersicht zurücknehmen", publishedAt: "Veröffentlicht am", pageCapacity: "Seiten im Entwurf / verfügbare Seiten", capacityExceeded: "Der Entwurf überschreitet die verfügbare Seitenzahl. Bitte zusätzliche Kapazität aktivieren oder Seiten entfernen.", removePage: "Seite entfernen" },
  en: { overview: "Overview", originalCard: "Original menu", displayChoice: "Choose view", textDraft: "Your text overview", saveText: "Save text draft", publishText: "Publish overview", unpublishText: "Unpublish overview", publishedAt: "Published", pageCapacity: "Draft pages / available pages", capacityExceeded: "The draft exceeds the available pages. Add capacity or remove pages.", removePage: "Remove page" },
  fr: { overview: "Aperçu", originalCard: "Carte originale", displayChoice: "Choisir l’affichage", textDraft: "Aperçu en texte", saveText: "Enregistrer le brouillon", publishText: "Publier l’aperçu", unpublishText: "Retirer l’aperçu", publishedAt: "Publié le", pageCapacity: "Pages du brouillon / pages disponibles", capacityExceeded: "Le brouillon dépasse le nombre de pages disponibles. Ajoutez de la capacité ou retirez des pages.", removePage: "Retirer la page" },
  it: { overview: "Panoramica", originalCard: "Menù originale", displayChoice: "Scegli vista", textDraft: "Panoramica testuale", saveText: "Salva bozza", publishText: "Pubblica panoramica", unpublishText: "Ritira panoramica", publishedAt: "Pubblicato il", pageCapacity: "Pagine in bozza / pagine disponibili", capacityExceeded: "La bozza supera le pagine disponibili. Aggiungi capacità o rimuovi pagine.", removePage: "Rimuovi pagina" },
  es: { overview: "Resumen", originalCard: "Carta original", displayChoice: "Elegir vista", textDraft: "Resumen de texto", saveText: "Guardar borrador", publishText: "Publicar resumen", unpublishText: "Retirar resumen", publishedAt: "Publicado el", pageCapacity: "Páginas del borrador / páginas disponibles", capacityExceeded: "El borrador supera las páginas disponibles. Añade capacidad o elimina páginas.", removePage: "Eliminar página" },
  zh: { overview: "概览", originalCard: "原版菜单", displayChoice: "选择视图", textDraft: "文字概览", saveText: "保存文字草稿", publishText: "发布概览", unpublishText: "撤回概览", publishedAt: "发布时间", pageCapacity: "草稿页数 / 可用页数", capacityExceeded: "草稿超过可用页数。请增加容量或移除页面。", removePage: "移除页面" },
  ko: { overview: "개요", originalCard: "원본 메뉴", displayChoice: "보기 선택", textDraft: "텍스트 개요", saveText: "초안 저장", publishText: "개요 게시", unpublishText: "개요 게시 취소", publishedAt: "게시일", pageCapacity: "초안 페이지 / 이용 가능 페이지", capacityExceeded: "초안이 이용 가능한 페이지 수를 초과했습니다. 용량을 추가하거나 페이지를 제거하세요.", removePage: "페이지 제거" },
} as const;

export type MenuMessageKey = keyof typeof messages.de | keyof typeof representationMessages.de;
export function menuMessage(language: string, key: MenuMessageKey): string {
  const locale = language.toLowerCase().split("-")[0] as keyof typeof messages;
  if (key in representationMessages.de) {
    return (representationMessages[locale] ?? representationMessages.de)[key as keyof typeof representationMessages.de];
  }
  return (messages[locale] ?? messages.de)[key as keyof typeof messages.de];
}
