import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migrationPath = new URL("../supabase/migrations/20260720001000_audit_and_safe_test_mode.sql", import.meta.url);
const appPath = new URL("../src/app/App.tsx", import.meta.url);
const pagePath = new URL("../src/modules/platform/PlatformAuditPage.tsx", import.meta.url);
const servicePath = new URL("../src/modules/platform/platformAdminService.ts", import.meta.url);
const dashboardPath = new URL("../src/modules/admin/pages/AdminDashboard.tsx", import.meta.url);
const rewardsPath = new URL("../src/modules/rewards/rewardService.ts", import.meta.url);
const loyaltyPath = new URL("../src/modules/loyalty/loyaltyService.ts", import.meta.url);
const kpiMigrationPath = new URL("../supabase/migrations/20260720003000_dashboard_kpis_and_redemption_status.sql", import.meta.url);

const migration = await readFile(migrationPath, "utf8");
const failureMigration = await readFile(new URL("../supabase/migrations/20260720002000_persist_pin_and_points_failures.sql", import.meta.url), "utf8");
const app = await readFile(appPath, "utf8");
const page = await readFile(pagePath, "utf8");
const service = await readFile(servicePath, "utf8");
const dashboard = await readFile(dashboardPath, "utf8");
const rewards = await readFile(rewardsPath, "utf8");
const loyalty = await readFile(loyaltyPath, "utf8");
const kpiMigration = await readFile(kpiMigrationPath, "utf8");

test("existing audit_log is extended with normalized event and test fields", () => {
  assert.match(migration, /alter table public\.audit_log/);
  for (const field of ["customer_id", "event_type", "status", "source", "entity_type", "entity_id", "request_id", "is_test_event", "test_session_id", "error_code", "error_message"]) {
    assert.match(migration, new RegExp(`add column if not exists ${field}`));
  }
  assert.doesNotMatch(migration, /create table (?:if not exists )?public\.(audit_events|platform_audit)/);
});

test("sensitive metadata is removed and audit writes stay server-side", () => {
  assert.match(migration, /audit_safe_metadata/);
  assert.match(migration, /customer_token\|referral_token\|session_token\|daily_pin\|pin_code\|pin_hash\|code_hash\|raw_code/);
  assert.match(migration, /revoke execute on function public\.write_audit_event[\s\S]*from public, anon, authenticated/);
  assert.doesNotMatch(service, /service[_-]?role/i);
});

test("customers cannot read or write audit rows directly", () => {
  assert.match(migration, /drop policy if exists "audit log member select"/);
  assert.match(migration, /create policy "audit log restaurant admin select"[\s\S]*to authenticated[\s\S]*is_restaurant_admin/);
  assert.doesNotMatch(migration, /grant (?:select|insert|update|delete).*audit_log.*anon/i);
});

test("test customers are controlled by a platform-only RPC", () => {
  assert.match(migration, /add column if not exists is_test_customer boolean not null default false/);
  assert.match(migration, /create or replace function public\.set_platform_customer_test_mode/);
  assert.match(migration, /current_platform_role/);
  assert.match(migration, /Test-Sitzungs-ID fehlt/);
  assert.match(migration, /revoke execute on function public\.set_platform_customer_test_mode\(uuid, boolean, text\) from public, anon/);
});

test("required successful flow events are generated by existing core tables", () => {
  for (const event of ["CUSTOMER_REGISTERED", "CUSTOMER_JOINED_RESTAURANT", "WELCOME_REWARD_CREATED", "POINTS_COLLECTION_STARTED", "POINTS_ADDED", "REWARD_UNLOCKED", "REDEMPTION_CODE_CREATED", "REWARD_REDEEMED", "COUPON_REDEEMED", "REFERRAL_CREATED", "REFERRAL_ACTIVATED"]) {
    assert.match(migration, new RegExp(event));
  }
  assert.match(migration, /audit_points_transactions_core_event/);
  assert.match(migration, /audit_redemption_codes_core_event/);
});

test("failed PIN and points attempts persist without exposing the submitted PIN", () => {
  assert.match(failureMigration, /persist_daily_pin_rejection/);
  assert.match(failureMigration, /DAILY_PIN_REJECTED/);
  assert.match(failureMigration, /AUTHORIZATION_DENIED/);
  assert.match(failureMigration, /POINTS_ADD_FAILED/);
  assert.match(failureMigration, /result_payload = request_result/);
  assert.doesNotMatch(failureMigration, /jsonb_build_object\([^)]*input_daily_pin/s);
  assert.ok((loyalty.match(/payload\?\.success === false/g) ?? []).length >= 2);
});

test("platform audit RPC is authenticated, role checked, filtered and bounded", () => {
  assert.match(migration, /create or replace function public\.get_platform_audit_events/);
  for (const filter of ["input_from", "input_to", "input_restaurant_id", "input_customer_id", "input_event_type", "input_status", "input_source", "input_actor_type", "input_test_only", "input_failed_only"]) {
    assert.match(migration, new RegExp(filter));
  }
  assert.match(migration, /limit least\(greatest\(coalesce\(input_limit, 100\), 1\), 500\)/);
  assert.match(migration, /revoke execute on function public\.get_platform_audit_events[\s\S]*from public, anon/);
  assert.match(migration, /grant execute on function public\.get_platform_audit_events[\s\S]*to authenticated/);
});

test("platform audit page uses protected route, filters and safe drawer", () => {
  assert.match(app, /path="\/admin\/platform\/audit"/);
  assert.match(app, /roleScope="platform"/);
  assert.match(page, /<AppDrawer/);
  assert.match(page, /Nur Testereignisse/);
  assert.match(page, /Nur fehlgeschlagen oder blockiert/);
  assert.match(page, /onKeyDown/);
  assert.doesNotMatch(page, /phone|Telefon|customer_token|Tages-PIN:\s*\{/i);
});

test("production dashboard KPIs exclude marked test customers", () => {
  assert.match(rewards, /get_restaurant_dashboard_kpis/);
  assert.ok((kpiMigration.match(/not c\.is_test_customer/g) ?? []).length >= 10);
  assert.match(kpiMigration, /public\.is_restaurant_member\(input_restaurant_id\)/);
  assert.match(dashboard, /newMembersThisWeek/);
  assert.match(migration, /get_bonus_boost_kpis[\s\S]*not c\.is_test_customer/);
});
