export type BusinessProfileKey = "restaurant" | "cafe" | "bakery" | "bubble_tea" | "ice_cream" | "retail" | "hair_salon" | "beauty" | "fitness" | "service" | "other";
export type GenerosityKey = "economical" | "standard" | "generous" | "premium";
export type WelcomeGiftOption = { key: string; label: string; category: string; estimatedValue: number; description: string };
export type GenerosityDefault = { welcomeGiftKey: string; rewardCategory: string; rewardTitle: string; estimatedValue: number; redemptionRatePercent: number };
export type BusinessProfile = {
  key: BusinessProfileKey;
  label: string;
  welcomeGiftOptions: WelcomeGiftOption[];
  redemptionCategories: string[];
  rewardTypes: readonly { key: string; label: string }[];
  generosityDefaults: Record<GenerosityKey, GenerosityDefault>;
  examples: string[];
};
export const DEFAULT_POINTS_PER_EURO: 10;
export const REDEMPTION_TYPE_OPTIONS: readonly { key: string; label: string }[];
export const GENEROSITY_OPTIONS: readonly { key: GenerosityKey; label: string }[];
export const BUSINESS_PROFILES: Readonly<Record<BusinessProfileKey, BusinessProfile>>;
export const BUSINESS_TYPE_OPTIONS: readonly { key: BusinessProfileKey; label: string }[];
export function businessProfileKeyFromValue(value: unknown): BusinessProfileKey;
export function isKnownBusinessType(value: unknown): boolean;
export function getBusinessProfile(value: unknown): BusinessProfile;
export function getWelcomeGiftOption(profile: BusinessProfile, key: string): WelcomeGiftOption | null;
export function isProfileWelcomeGiftKey(key: unknown): boolean;
export function reconcileBusinessProfileSelections(input: { businessType: unknown; welcomeGiftKey: string; rewardCategory: string }): { welcomeGiftKey: string; rewardCategory: string; changed: boolean };
export function createBonusProgramSuggestion(input: { businessType: unknown; generosity?: GenerosityKey; averagePurchase: number; pointsPerEuro?: number; redemptionType?: string; redemptionRatePercent?: number | null }): {
  businessType: string;
  businessProfileKey: BusinessProfileKey;
  generosity: GenerosityKey;
  welcomeGift: WelcomeGiftOption | null;
  rewardCategory: string;
  rewardTitle: string;
  estimatedValue: number;
  redemptionType: string;
  redemptionRatePercent: number;
  pointsPerEuro: number;
  requiredPoints: number;
  estimatedConsumption: number;
  economicsStatus: string;
  description: string;
};
