type ProMessages = Record<string, string>;

const de: ProMessages = {
  title: "Pro-Freigaben", description: "Länderfreigaben, Pilotzugänge und Prüfverlauf sicher verwalten.",
  loading: "Pro-Freigaben werden geladen …", loadError: "Pro-Freigaben konnten nicht geladen werden.", retry: "Erneut versuchen",
  countries: "Länderstatus", locked: "Pro gesperrt", released: "Pro freigegeben", change: "Status verwalten",
  lastChange: "Letzte Änderung", actor: "Akteur", reason: "Begründung", noReason: "Noch keine Änderung dokumentiert",
  entitlements: "Berechtigungen", paid: "Bezahlt", trial: "Testphase", pilot: "Pilot", testOnly: "TEST_ONLY", test_only: "TEST_ONLY",
  realBusinesses: "Echte Pilotbetriebe", businessSearch: "Betrieb suchen", noBusinesses: "Keine passenden echten Betriebe gefunden.",
  createPilot: "Pilotzugang vorbereiten", storedPlan: "Gespeicherter Plan", effectivePlan: "Wirksamer Plan", locations: "Standorte",
  testOnlyTitle: "Interne TEST_ONLY-Betriebe", noTestOnly: "Keine exakt serverseitig markierten TEST_ONLY-Betriebe gefunden.",
  grants: "Grant-Verlauf", audit: "Commercial-Audit", noGrants: "Keine Berechtigungen für diesen Filter.", noAudit: "Noch keine Commercial-Audit-Einträge.",
  all: "Alle", active: "Aktiv", scheduled: "Geplant", expired: "Abgelaufen", revoked: "Widerrufen",
  countryDrawer: "Länderfreigabe verwalten", pilotDrawer: "Pilotzugang verwalten", testDrawer: "TEST_ONLY-Zugang verwalten",
  impact: "Auswirkungsvorschau", releaseImpact: "Eine Länderfreigabe allein aktiviert keinen Basic-Betrieb. Erst eine gültige Paid-, Trial- oder Pilotberechtigung kann Pro wirksam machen.",
  lockImpact: "Pro wird für dieses Land serverseitig gesperrt. Gespeicherte Zustände und Daten bleiben erhalten.",
  pilotImpact: "Der zeitlich begrenzte Zugang erzeugt keine Zahlung und keine automatische Verlängerung.",
  recentAuth: "Diese Hochrisiko-Aktion verlangt serverseitig eine Anmeldung innerhalb der letzten 10 Minuten.",
  confirmation: "Exakter Bestätigungstext", enterReason: "Interne Begründung mit mindestens 10 Zeichen", cancel: "Abbrechen", submit: "Bestätigt ausführen",
  duration: "Laufzeit", days30: "30 Tage", days60: "60 Tage", days90: "90 Tage", start: "Start", end: "Ablauf",
  validation: "Begründung und exakter Bestätigungstext sind erforderlich.", conflict: "Der Zustand hat sich geändert. Daten wurden neu geladen.", recentError: "Bitte melde dich erneut an und wiederhole die Aktion.", saveError: "Aktion wurde serverseitig abgelehnt. Pro bleibt gesperrt.",
  refresh: "Aktualisieren", extend: "Verlängern", revoke: "Widerrufen", grant: "Zugang vorbereiten", result: "Ergebnis", empty: "Keine Einträge",
};

const localized: Record<string, Partial<ProMessages>> = {
  en: { title:"Pro releases",description:"Safely manage country releases, pilot access and audit history.",loading:"Loading Pro releases …",loadError:"Pro releases could not be loaded.",retry:"Try again",countries:"Country status",locked:"Pro locked",released:"Pro released",change:"Manage status",lastChange:"Last change",actor:"Actor",reason:"Reason",noReason:"No change documented yet",entitlements:"Entitlements",paid:"Paid",trial:"Trial",pilot:"Pilot",testOnly:"TEST_ONLY",realBusinesses:"Real pilot businesses",businessSearch:"Search business",noBusinesses:"No matching real businesses found.",createPilot:"Prepare pilot access",storedPlan:"Stored plan",effectivePlan:"Effective plan",locations:"Locations",testOnlyTitle:"Internal TEST_ONLY businesses",noTestOnly:"No exactly server-marked TEST_ONLY businesses found.",grants:"Grant history",audit:"Commercial audit",noGrants:"No entitlements for this filter.",noAudit:"No commercial audit entries yet.",all:"All",active:"Active",scheduled:"Scheduled",expired:"Expired",revoked:"Revoked",countryDrawer:"Manage country release",pilotDrawer:"Manage pilot access",testDrawer:"Manage TEST_ONLY access",impact:"Impact preview",releaseImpact:"A country release alone does not upgrade a Basic business. Valid paid, trial or pilot entitlement is also required.",lockImpact:"Pro will be locked server-side for this country. Stored states and data remain intact.",pilotImpact:"Time-limited access creates no payment and no automatic renewal.",recentAuth:"This high-risk action requires server-side authentication within the last 10 minutes.",confirmation:"Exact confirmation text",enterReason:"Internal reason of at least 10 characters",cancel:"Cancel",submit:"Execute confirmed action",duration:"Duration",days30:"30 days",days60:"60 days",days90:"90 days",start:"Start",end:"Expiry",validation:"A reason and exact confirmation are required.",conflict:"The state changed. Data was reloaded.",recentError:"Please sign in again and repeat the action.",saveError:"The server rejected the action. Pro remains locked.",refresh:"Refresh",extend:"Extend",revoke:"Revoke",grant:"Prepare access",result:"Result",empty:"No entries" },
  fr: { title:"Autorisations Pro",description:"Gérer en sécurité les pays, pilotes et l’audit.",loading:"Chargement des autorisations Pro…",loadError:"Impossible de charger les autorisations Pro.",retry:"Réessayer",countries:"Statut des pays",locked:"Pro verrouillé",released:"Pro activé",change:"Gérer le statut",lastChange:"Dernière modification",actor:"Acteur",reason:"Motif",noReason:"Aucune modification documentée",entitlements:"Autorisations",paid:"Payé",trial:"Essai",pilot:"Pilote",testOnly:"TEST_ONLY",test_only:"TEST_ONLY",realBusinesses:"Établissements pilotes réels",businessSearch:"Rechercher un établissement",noBusinesses:"Aucun établissement réel correspondant.",createPilot:"Préparer l’accès pilote",storedPlan:"Forfait enregistré",effectivePlan:"Forfait effectif",locations:"Établissements",testOnlyTitle:"Établissements TEST_ONLY internes",noTestOnly:"Aucun établissement TEST_ONLY marqué exactement par le serveur.",grants:"Historique des autorisations",audit:"Audit commercial",noGrants:"Aucune autorisation pour ce filtre.",noAudit:"Aucune entrée d’audit commercial.",all:"Tous",active:"Actif",scheduled:"Planifié",expired:"Expiré",revoked:"Révoqué",countryDrawer:"Gérer l’activation du pays",pilotDrawer:"Gérer l’accès pilote",testDrawer:"Gérer l’accès TEST_ONLY",impact:"Aperçu de l’impact",releaseImpact:"L’activation d’un pays ne met aucun établissement Basic à niveau. Une autorisation payée, d’essai ou pilote valide reste nécessaire.",lockImpact:"Pro sera verrouillé côté serveur pour ce pays. Les états et données enregistrés restent intacts.",pilotImpact:"L’accès temporaire ne crée ni paiement ni renouvellement automatique.",recentAuth:"Cette action à haut risque exige une authentification serveur datant de moins de 10 minutes.",confirmation:"Texte de confirmation exact",enterReason:"Motif interne d’au moins 10 caractères",cancel:"Annuler",submit:"Exécuter l’action confirmée",duration:"Durée",days30:"30 jours",days60:"60 jours",days90:"90 jours",start:"Début",end:"Expiration",validation:"Un motif et le texte de confirmation exact sont requis.",conflict:"L’état a changé. Les données ont été rechargées.",recentError:"Reconnectez-vous puis répétez l’action.",saveError:"Le serveur a refusé l’action. Pro reste verrouillé.",refresh:"Actualiser",extend:"Prolonger",revoke:"Révoquer",grant:"Préparer l’accès",result:"Résultat",empty:"Aucune entrée" },
  it: { title:"Abilitazioni Pro",description:"Gestisci in sicurezza paesi, accessi pilota e audit.",loading:"Caricamento abilitazioni Pro…",loadError:"Impossibile caricare le abilitazioni Pro.",retry:"Riprova",countries:"Stato paesi",locked:"Pro bloccato",released:"Pro abilitato",change:"Gestisci stato",lastChange:"Ultima modifica",actor:"Attore",reason:"Motivo",noReason:"Nessuna modifica documentata",entitlements:"Abilitazioni",paid:"A pagamento",trial:"Prova",pilot:"Pilota",testOnly:"TEST_ONLY",test_only:"TEST_ONLY",realBusinesses:"Attività pilota reali",businessSearch:"Cerca attività",noBusinesses:"Nessuna attività reale corrispondente.",createPilot:"Prepara accesso pilota",storedPlan:"Piano salvato",effectivePlan:"Piano effettivo",locations:"Sedi",testOnlyTitle:"Attività TEST_ONLY interne",noTestOnly:"Nessuna attività TEST_ONLY marcata esattamente dal server.",grants:"Cronologia accessi",audit:"Audit commerciale",noGrants:"Nessuna abilitazione per questo filtro.",noAudit:"Nessuna voce di audit commerciale.",all:"Tutti",active:"Attivo",scheduled:"Programmato",expired:"Scaduto",revoked:"Revocato",countryDrawer:"Gestisci abilitazione paese",pilotDrawer:"Gestisci accesso pilota",testDrawer:"Gestisci accesso TEST_ONLY",impact:"Anteprima impatto",releaseImpact:"L’abilitazione del paese non aggiorna da sola un’attività Basic. Serve anche un accesso a pagamento, di prova o pilota valido.",lockImpact:"Pro viene bloccato lato server per questo paese. Stati e dati salvati restano intatti.",pilotImpact:"L’accesso temporaneo non crea pagamenti né rinnovi automatici.",recentAuth:"Questa azione ad alto rischio richiede un’autenticazione server negli ultimi 10 minuti.",confirmation:"Testo di conferma esatto",enterReason:"Motivo interno di almeno 10 caratteri",cancel:"Annulla",submit:"Esegui azione confermata",duration:"Durata",days30:"30 giorni",days60:"60 giorni",days90:"90 giorni",start:"Inizio",end:"Scadenza",validation:"Sono richiesti motivo e testo di conferma esatto.",conflict:"Lo stato è cambiato. I dati sono stati ricaricati.",recentError:"Accedi nuovamente e ripeti l’azione.",saveError:"Il server ha rifiutato l’azione. Pro resta bloccato.",refresh:"Aggiorna",extend:"Estendi",revoke:"Revoca",grant:"Prepara accesso",result:"Risultato",empty:"Nessuna voce" },
  es: { title:"Habilitaciones Pro",description:"Gestiona países, pilotos y auditoría de forma segura.",loading:"Cargando habilitaciones Pro…",loadError:"No se pudieron cargar las habilitaciones Pro.",retry:"Reintentar",countries:"Estado de países",locked:"Pro bloqueado",released:"Pro habilitado",change:"Gestionar estado",lastChange:"Último cambio",actor:"Actor",reason:"Motivo",noReason:"Aún no hay cambios documentados",entitlements:"Habilitaciones",paid:"De pago",trial:"Prueba",pilot:"Piloto",testOnly:"TEST_ONLY",test_only:"TEST_ONLY",realBusinesses:"Negocios piloto reales",businessSearch:"Buscar negocio",noBusinesses:"No hay negocios reales coincidentes.",createPilot:"Preparar acceso piloto",storedPlan:"Plan guardado",effectivePlan:"Plan efectivo",locations:"Ubicaciones",testOnlyTitle:"Negocios TEST_ONLY internos",noTestOnly:"No hay negocios TEST_ONLY marcados exactamente por el servidor.",grants:"Historial de accesos",audit:"Auditoría comercial",noGrants:"No hay habilitaciones para este filtro.",noAudit:"Aún no hay entradas de auditoría comercial.",all:"Todos",active:"Activo",scheduled:"Programado",expired:"Caducado",revoked:"Revocado",countryDrawer:"Gestionar habilitación del país",pilotDrawer:"Gestionar acceso piloto",testDrawer:"Gestionar acceso TEST_ONLY",impact:"Vista previa del impacto",releaseImpact:"Habilitar un país no actualiza por sí solo un negocio Basic. También se requiere un acceso válido de pago, prueba o piloto.",lockImpact:"Pro se bloqueará en el servidor para este país. Los estados y datos guardados permanecen intactos.",pilotImpact:"El acceso temporal no crea pagos ni renovaciones automáticas.",recentAuth:"Esta acción de alto riesgo requiere autenticación del servidor en los últimos 10 minutos.",confirmation:"Texto de confirmación exacto",enterReason:"Motivo interno de al menos 10 caracteres",cancel:"Cancelar",submit:"Ejecutar acción confirmada",duration:"Duración",days30:"30 días",days60:"60 días",days90:"90 días",start:"Inicio",end:"Caducidad",validation:"Se requieren el motivo y el texto de confirmación exacto.",conflict:"El estado cambió. Los datos se volvieron a cargar.",recentError:"Vuelve a iniciar sesión y repite la acción.",saveError:"El servidor rechazó la acción. Pro sigue bloqueado.",refresh:"Actualizar",extend:"Ampliar",revoke:"Revocar",grant:"Preparar acceso",result:"Resultado",empty:"Sin entradas" },
  zh: { title:"Pro 授权",description:"安全管理国家发布、试点访问和审计记录。",loading:"正在加载 Pro 授权…",loadError:"无法加载 Pro 授权。",retry:"重试",countries:"国家状态",locked:"Pro 已锁定",released:"Pro 已发布",change:"管理状态",lastChange:"最近更改",actor:"操作人",reason:"原因",noReason:"尚无已记录的更改",entitlements:"授权",paid:"付费",trial:"试用",pilot:"试点",testOnly:"TEST_ONLY",test_only:"TEST_ONLY",realBusinesses:"真实试点商户",businessSearch:"搜索商户",noBusinesses:"没有匹配的真实商户。",createPilot:"准备试点访问",storedPlan:"已存套餐",effectivePlan:"生效套餐",locations:"门店",testOnlyTitle:"内部 TEST_ONLY 商户",noTestOnly:"没有服务器精确标记的 TEST_ONLY 商户。",grants:"授权历史",audit:"商业审计",noGrants:"此筛选条件下没有授权。",noAudit:"暂无商业审计记录。",all:"全部",active:"有效",scheduled:"已计划",expired:"已到期",revoked:"已撤销",countryDrawer:"管理国家发布",pilotDrawer:"管理试点访问",testDrawer:"管理 TEST_ONLY 访问",impact:"影响预览",releaseImpact:"仅发布国家不会升级 Basic 商户，还必须具备有效的付费、试用或试点授权。",lockImpact:"该国家的 Pro 将在服务器端锁定，已保存状态和数据保持不变。",pilotImpact:"限时访问不会产生付款或自动续期。",recentAuth:"此高风险操作要求最近 10 分钟内完成服务器端身份验证。",confirmation:"精确确认文本",enterReason:"至少 10 个字符的内部原因",cancel:"取消",submit:"执行已确认操作",duration:"期限",days30:"30 天",days60:"60 天",days90:"90 天",start:"开始",end:"到期",validation:"必须填写原因和精确确认文本。",conflict:"状态已更改，数据已重新加载。",recentError:"请重新登录后再次执行操作。",saveError:"服务器拒绝了操作，Pro 保持锁定。",refresh:"刷新",extend:"延长",revoke:"撤销",grant:"准备访问",result:"结果",empty:"无记录" },
  ko: { title:"Pro 승인",description:"국가 출시, 파일럿 접근 및 감사 기록을 안전하게 관리합니다.",loading:"Pro 승인을 불러오는 중…",loadError:"Pro 승인을 불러올 수 없습니다.",retry:"다시 시도",countries:"국가 상태",locked:"Pro 잠김",released:"Pro 출시됨",change:"상태 관리",lastChange:"최근 변경",actor:"작업자",reason:"사유",noReason:"기록된 변경이 없습니다",entitlements:"승인",paid:"유료",trial:"체험",pilot:"파일럿",testOnly:"TEST_ONLY",test_only:"TEST_ONLY",realBusinesses:"실제 파일럿 사업장",businessSearch:"사업장 검색",noBusinesses:"일치하는 실제 사업장이 없습니다.",createPilot:"파일럿 접근 준비",storedPlan:"저장된 요금제",effectivePlan:"적용 요금제",locations:"지점",testOnlyTitle:"내부 TEST_ONLY 사업장",noTestOnly:"서버에서 정확히 표시된 TEST_ONLY 사업장이 없습니다.",grants:"승인 기록",audit:"상업 감사",noGrants:"이 필터에 해당하는 승인이 없습니다.",noAudit:"상업 감사 기록이 없습니다.",all:"전체",active:"활성",scheduled:"예정",expired:"만료",revoked:"철회",countryDrawer:"국가 출시 관리",pilotDrawer:"파일럿 접근 관리",testDrawer:"TEST_ONLY 접근 관리",impact:"영향 미리보기",releaseImpact:"국가 출시만으로 Basic 사업장이 업그레이드되지 않습니다. 유효한 유료, 체험 또는 파일럿 권한도 필요합니다.",lockImpact:"이 국가의 Pro는 서버에서 잠깁니다. 저장된 상태와 데이터는 유지됩니다.",pilotImpact:"기간 제한 접근은 결제나 자동 갱신을 만들지 않습니다.",recentAuth:"이 고위험 작업은 최근 10분 이내의 서버 인증이 필요합니다.",confirmation:"정확한 확인 문구",enterReason:"10자 이상의 내부 사유",cancel:"취소",submit:"확인된 작업 실행",duration:"기간",days30:"30일",days60:"60일",days90:"90일",start:"시작",end:"만료",validation:"사유와 정확한 확인 문구가 필요합니다.",conflict:"상태가 변경되어 데이터를 다시 불러왔습니다.",recentError:"다시 로그인한 후 작업을 반복하세요.",saveError:"서버가 작업을 거부했습니다. Pro는 잠긴 상태입니다.",refresh:"새로고침",extend:"연장",revoke:"철회",grant:"접근 준비",result:"결과",empty:"항목 없음" },
};

export function proControlCenterMessages(language: string): ProMessages {
  return Object.assign({}, de, localized[language] ?? {}) as ProMessages;
}

export const proControlCenterLanguages = localized;
export const proControlCenterGerman = de;
