const keys = ["title", "offerAddon", "customerAddon", "netMonth", "offers", "customers", "unavailable", "window", "trial", "locked"];
const rows = {
  de: ["Tarifkatalog", "Angebots-Add-on", "Kunden-Add-on", "netto/Monat, USt. exklusiv", "Angebote", "Kundenkonten", "Tarifkatalog derzeit nicht verfügbar.", "Aktive eindeutige Kundenkonten innerhalb der jeweils zurückliegenden 365 Tage.", "BASIC: Ein berechtigter Platform Admin kann nach bestandenen Freigaben manuell eine Testphase von einem oder drei Kalendermonaten aktivieren. Registrierung startet keinen Trial. Add-ons haben keinen Trial; PRO bleibt ein eigener Ablauf.", "Zahlungsaktivierung ist noch gesperrt. Hier wird nichts gebucht oder aktiviert."],
  en: ["Plan catalog", "Offer add-on", "Customer add-on", "net/month, VAT excluded", "offers", "customer accounts", "Plan catalog currently unavailable.", "Unique active customer accounts within the preceding 365 days.", "BASIC: Once all approval gates have passed, an authorized platform admin may manually activate a trial of one or three calendar months. Registration does not start a trial. Add-ons have no trial; PRO remains a separate flow.", "Payment activation remains locked. Nothing is purchased or activated here."],
  fr: ["Catalogue des forfaits", "Option offres", "Option clients", "net/mois, hors TVA", "offres", "comptes clients", "Catalogue actuellement indisponible.", "Comptes clients actifs uniques au cours des 365 jours précédents.", "BASIC : après validation de tous les contrôles, un administrateur de plateforme autorisé peut activer manuellement un essai d’un ou trois mois calendaires. L’inscription ne démarre aucun essai. Les options n’ont pas d’essai ; PRO suit un parcours distinct.", "L’activation du paiement reste bloquée. Aucun achat ni aucune activation ici."],
  it: ["Catalogo piani", "Opzione offerte", "Opzione clienti", "netti/mese, IVA esclusa", "offerte", "account cliente", "Catalogo attualmente non disponibile.", "Account cliente attivi unici nei 365 giorni precedenti.", "BASIC: dopo il superamento di tutti i controlli, un amministratore di piattaforma autorizzato può attivare manualmente una prova di uno o tre mesi di calendario. La registrazione non avvia una prova. Le opzioni non hanno prova; PRO segue un percorso separato.", "L’attivazione dei pagamenti resta bloccata. Qui non si acquista né si attiva nulla."],
  es: ["Catálogo de planes", "Complemento de ofertas", "Complemento de clientes", "netos/mes, IVA excluido", "ofertas", "cuentas de clientes", "Catálogo no disponible actualmente.", "Cuentas de clientes activas únicas durante los 365 días anteriores.", "BASIC: tras superar todas las comprobaciones, un administrador de plataforma autorizado puede activar manualmente una prueba de uno o tres meses naturales. El registro no inicia una prueba. Los complementos no tienen prueba; PRO sigue un proceso separado.", "La activación de pagos sigue bloqueada. Aquí no se compra ni se activa nada."],
  zh: ["套餐目录", "优惠容量附加包", "客户容量附加包", "净价/月，不含增值税", "项优惠", "个客户账户", "套餐目录暂不可用。", "在此前365天内活跃的唯一客户账户。", "BASIC：通过全部审核条件后，获授权的平台管理员可手动启用一个或三个自然月的试用期。注册不会启动试用。附加包没有试用期；PRO采用独立流程。", "支付激活仍被锁定。此处不会购买或激活任何服务。"],
  ko: ["요금제 목록", "혜택 용량 추가 옵션", "고객 용량 추가 옵션", "월 순가격, 부가세 별도", "개 혜택", "개 고객 계정", "현재 요금제 목록을 이용할 수 없습니다.", "직전 365일 이내의 고유 활성 고객 계정입니다.", "BASIC: 모든 승인 조건을 통과한 뒤 권한 있는 플랫폼 관리자가 1개월 또는 3개월의 체험 기간을 수동으로 활성화할 수 있습니다. 가입만으로 체험이 시작되지 않습니다. 추가 옵션에는 체험 기간이 없으며 PRO는 별도 절차입니다.", "결제 활성화는 잠겨 있습니다. 여기서는 구매하거나 활성화하지 않습니다."],
};
export function billingCatalogMessages(language) {
  return Object.fromEntries(keys.map((key, index) => [key, (rows[language] ?? rows.de)[index]]));
}
