const keys = ["title", "offerAddon", "customerAddon", "netMonth", "offers", "customers", "unavailable", "window", "trial", "locked"];
const rows = {
  de: ["Tarifkatalog", "Angebots-Add-on", "Kunden-Add-on", "netto/Monat, USt. exklusiv", "Angebote", "Kundenkonten", "Tarifkatalog derzeit nicht verfügbar.", "Aktive eindeutige Kundenkonten innerhalb der jeweils zurückliegenden 365 Tage.", "BASIC und PRO: Der erste vollständige Kalendermonat ist erst nach bestätigter Provideraktivierung kostenlos, höchstens einmal pro Unternehmen. Add-ons sind nicht kostenlos. Registrierung startet keinen Trial.", "Zahlungsaktivierung ist noch gesperrt. Hier wird nichts gebucht oder aktiviert."],
  en: ["Plan catalog", "Offer add-on", "Customer add-on", "net/month, VAT excluded", "offers", "customer accounts", "Plan catalog currently unavailable.", "Unique active customer accounts within the preceding 365 days.", "BASIC and PRO: The first full calendar month is free only after confirmed provider activation, at most once per company. Add-ons are not free. Registration does not start a trial.", "Payment activation remains locked. Nothing is purchased or activated here."],
  fr: ["Catalogue des forfaits", "Option offres", "Option clients", "net/mois, hors TVA", "offres", "comptes clients", "Catalogue actuellement indisponible.", "Comptes clients actifs uniques au cours des 365 jours précédents.", "BASIC et PRO : le premier mois calendaire complet est gratuit uniquement après activation confirmée par le prestataire, une seule fois par entreprise. Les options sont payantes. L’inscription ne démarre aucun essai.", "L’activation du paiement reste bloquée. Aucun achat ni aucune activation ici."],
  it: ["Catalogo piani", "Opzione offerte", "Opzione clienti", "netti/mese, IVA esclusa", "offerte", "account cliente", "Catalogo attualmente non disponibile.", "Account cliente attivi unici nei 365 giorni precedenti.", "BASIC e PRO: il primo mese di calendario completo è gratuito solo dopo l’attivazione confermata dal fornitore, una sola volta per azienda. Le opzioni non sono gratuite. La registrazione non avvia una prova.", "L’attivazione dei pagamenti resta bloccata. Qui non si acquista né si attiva nulla."],
  es: ["Catálogo de planes", "Complemento de ofertas", "Complemento de clientes", "netos/mes, IVA excluido", "ofertas", "cuentas de clientes", "Catálogo no disponible actualmente.", "Cuentas de clientes activas únicas durante los 365 días anteriores.", "BASIC y PRO: el primer mes natural completo es gratuito solo tras la activación confirmada por el proveedor, una vez por empresa. Los complementos no son gratuitos. El registro no inicia una prueba.", "La activación de pagos sigue bloqueada. Aquí no se compra ni se activa nada."],
  zh: ["套餐目录", "优惠容量附加包", "客户容量附加包", "净价/月，不含增值税", "项优惠", "个客户账户", "套餐目录暂不可用。", "在此前365天内活跃的唯一客户账户。", "BASIC和PRO：仅在支付服务商确认激活后，第一个完整日历月免费，每家企业最多一次。附加包不免费。注册不会启动试用。", "支付激活仍被锁定。此处不会购买或激活任何服务。"],
  ko: ["요금제 목록", "혜택 용량 추가 옵션", "고객 용량 추가 옵션", "월 순가격, 부가세 별도", "개 혜택", "개 고객 계정", "현재 요금제 목록을 이용할 수 없습니다.", "직전 365일 이내의 고유 활성 고객 계정입니다.", "BASIC 및 PRO: 결제 제공자의 활성화 확인 후 첫 한 달만 무료이며 기업당 한 번만 제공됩니다. 추가 옵션은 무료가 아닙니다. 가입만으로 체험이 시작되지 않습니다.", "결제 활성화는 잠겨 있습니다. 여기서는 구매하거나 활성화하지 않습니다."],
};
export function billingCatalogMessages(language) {
  return Object.fromEntries(keys.map((key, index) => [key, (rows[language] ?? rows.de)[index]]));
}
