import { normalizeUiLanguage } from "../../shared/i18n/language.mjs";

const MESSAGES = Object.freeze({
  de: {
    title: "Tarif & Kapazität", description: "Dein aktueller Tarif und die serverseitig ermittelte Nutzung.", back: "Zurück", loading: "Kapazität wird geladen …", error: "Tarif und Kapazität konnten gerade nicht geladen werden.", retry: "Erneut versuchen", plan: "Aktueller Tarif", netMonth: "{price} netto pro Monat", country: "Land", commercial: "PRO-Verfügbarkeit", locked: "Noch nicht freigegeben", released: "Freigegeben", offers: "Angebote", customers: "Aktive Kunden", used: "{usage} von {limit} verwendet", included: "{value} im Tarif enthalten", addons: "{units} Add-on-Einheiten aktiv", addonCapacity: "+{value} durch Add-ons", total: "Gesamtkapazität: {value}", remaining: "Noch {value} verfügbar", window: "Rollierender Zeitraum: letzte {days} Tage", asOf: "Stand: {date}", available: "Kapazität verfügbar", warning80: "Kapazität zu mindestens 80 % genutzt", warning90: "Kapazität zu mindestens 90 % genutzt", atLimit: "Kapazitätslimit erreicht", overLimit: "Kapazität überschritten", offerAt: "Deine aktuelle Angebotskapazität ist erreicht. Zusätzliche Kapazität kann erst nach einer aktiven Buchung zählen.", customerAt: "Deine aktuelle Kundenkapazität ist erreicht. Zusätzliche Kapazität kann erst nach einer aktiven Buchung zählen.", offerOver: "Du verwendest {usage} von aktuell {limit} verfügbaren Angeboten. Bestehende Angebote bleiben erhalten. Neue Angebote können erst aktiviert werden, wenn deine Nutzung wieder innerhalb des Limits liegt oder zusätzliche Kapazität aktiv gebucht wurde.", customerOver: "Du verwendest {usage} von aktuell {limit} verfügbaren Kundenplätzen. Bestehende Kunden, Punkte und Einlösungen bleiben erhalten. Eine neue erste Aktivität ist erst innerhalb des Limits oder nach aktiver Kapazitätserhöhung möglich.", increase: "Kapazität erhöhen", drawerTitle: "Zusätzliche Kapazität", drawerDescription: "Informationen zur späteren Add-on-Buchung. Es wird noch nichts bestellt.", offerAddon: "Angebots-Add-on", customerAddon: "Kunden-Add-on", addonLine: "+{value} für {price} netto pro Monat", noPurchase: "Stripe und automatische Abrechnung sind nicht aktiviert. Diese Ansicht ändert weder Tarif noch Kapazität.", cancel: "Schließen", warningTitle: "Kapazitätswarnungen", warningPending: "In-App- und E-Mail-Warnungen sind noch nicht aktiviert. Wiederholung, Cooldown und Entwarnung benötigen eine Founder-Entscheidung.", forecastPending: "Die 7-Tage-Prognose bleibt deaktiviert, bis die erforderliche Datenbasis und der vollständige Versandvertrag bereitstehen.", payment: "Zahlungsstatus", unavailable: "Nicht verfügbar",
  },
  en: {
    title: "Plan & capacity", description: "Your current plan and server-calculated usage.", back: "Back", loading: "Loading capacity …", error: "Plan and capacity could not be loaded.", retry: "Try again", plan: "Current plan", netMonth: "{price} net per month", country: "Country", commercial: "PRO availability", locked: "Not released yet", released: "Released", offers: "Offers", customers: "Active customers", used: "{usage} of {limit} used", included: "{value} included in the plan", addons: "{units} add-on units active", addonCapacity: "+{value} through add-ons", total: "Total capacity: {value}", remaining: "{value} remaining", window: "Rolling period: last {days} days", asOf: "As of: {date}", available: "Capacity available", warning80: "Capacity is at least 80% used", warning90: "Capacity is at least 90% used", atLimit: "Capacity limit reached", overLimit: "Capacity exceeded", offerAt: "Your current offer capacity has been reached. Additional capacity counts only after an active booking.", customerAt: "Your current customer capacity has been reached. Additional capacity counts only after an active booking.", offerOver: "You are using {usage} of {limit} currently available offers. Existing offers remain available. New offers can be activated only after usage returns within the limit or additional capacity becomes active.", customerOver: "You are using {usage} of {limit} currently available customer places. Existing customers, points and redemptions remain available. A new first activity is possible only within the limit or after additional capacity becomes active.", increase: "Increase capacity", drawerTitle: "Additional capacity", drawerDescription: "Information for a later add-on booking. Nothing will be ordered.", offerAddon: "Offer add-on", customerAddon: "Customer add-on", addonLine: "+{value} for {price} net per month", noPurchase: "Stripe and automatic billing are not active. This view changes neither plan nor capacity.", cancel: "Close", warningTitle: "Capacity warnings", warningPending: "In-app and email warnings are not active yet. Repetition, cooldown and clearing require a Founder decision.", forecastPending: "The 7-day forecast stays disabled until the required data basis and complete delivery contract are ready.", payment: "Payment status", unavailable: "Unavailable",
  },
  fr: {
    title: "Forfait et capacité", description: "Votre forfait actuel et l’utilisation calculée par le serveur.", back: "Retour", loading: "Chargement de la capacité…", error: "Le forfait et la capacité ne peuvent pas être chargés.", retry: "Réessayer", plan: "Forfait actuel", netMonth: "{price} HT par mois", country: "Pays", commercial: "Disponibilité de PRO", locked: "Pas encore disponible", released: "Disponible", offers: "Offres", customers: "Clients actifs", used: "{usage} sur {limit} utilisés", included: "{value} inclus dans le forfait", addons: "{units} unités supplémentaires actives", addonCapacity: "+{value} via les options", total: "Capacité totale : {value}", remaining: "Encore {value} disponibles", window: "Période glissante : {days} derniers jours", asOf: "État au : {date}", available: "Capacité disponible", warning80: "Capacité utilisée à au moins 80 %", warning90: "Capacité utilisée à au moins 90 %", atLimit: "Limite atteinte", overLimit: "Capacité dépassée", offerAt: "Votre capacité d’offres est atteinte. La capacité supplémentaire ne compte qu’après une réservation active.", customerAt: "Votre capacité clients est atteinte. La capacité supplémentaire ne compte qu’après une réservation active.", offerOver: "Vous utilisez {usage} offres sur {limit} disponibles. Les offres existantes restent disponibles. Une nouvelle offre exige un retour sous la limite ou une capacité supplémentaire active.", customerOver: "Vous utilisez {usage} places clients sur {limit}. Les clients, points et utilisations existants restent disponibles. Une première activité supplémentaire exige une capacité disponible.", increase: "Augmenter la capacité", drawerTitle: "Capacité supplémentaire", drawerDescription: "Informations pour une option ultérieure. Aucune commande n’est passée.", offerAddon: "Option offres", customerAddon: "Option clients", addonLine: "+{value} pour {price} HT par mois", noPurchase: "Stripe et la facturation automatique ne sont pas activés. Cette vue ne modifie rien.", cancel: "Fermer", warningTitle: "Alertes de capacité", warningPending: "Les alertes dans l’application et par e-mail ne sont pas encore actives. Répétition, délai et fin d’alerte nécessitent une décision du Founder.", forecastPending: "La prévision à 7 jours reste désactivée jusqu’à disponibilité des données et du contrat d’envoi.", payment: "État du paiement", unavailable: "Indisponible",
  },
  it: {
    title: "Piano e capacità", description: "Il piano attuale e l’utilizzo calcolato dal server.", back: "Indietro", loading: "Caricamento capacità…", error: "Impossibile caricare piano e capacità.", retry: "Riprova", plan: "Piano attuale", netMonth: "{price} netti al mese", country: "Paese", commercial: "Disponibilità PRO", locked: "Non ancora disponibile", released: "Disponibile", offers: "Offerte", customers: "Clienti attivi", used: "{usage} di {limit} utilizzati", included: "{value} inclusi nel piano", addons: "{units} unità aggiuntive attive", addonCapacity: "+{value} tramite add-on", total: "Capacità totale: {value}", remaining: "Ancora {value} disponibili", window: "Periodo mobile: ultimi {days} giorni", asOf: "Aggiornato al: {date}", available: "Capacità disponibile", warning80: "Capacità utilizzata almeno all’80%", warning90: "Capacità utilizzata almeno al 90%", atLimit: "Limite raggiunto", overLimit: "Capacità superata", offerAt: "La capacità delle offerte è stata raggiunta. La capacità aggiuntiva conta solo dopo un acquisto attivo.", customerAt: "La capacità clienti è stata raggiunta. La capacità aggiuntiva conta solo dopo un acquisto attivo.", offerOver: "Stai utilizzando {usage} offerte su {limit} disponibili. Le offerte esistenti restano disponibili. Per attivarne altre occorre rientrare nel limite o attivare capacità aggiuntiva.", customerOver: "Stai utilizzando {usage} posti cliente su {limit}. Clienti, punti e riscatti esistenti restano disponibili. Una nuova prima attività richiede capacità disponibile.", increase: "Aumenta capacità", drawerTitle: "Capacità aggiuntiva", drawerDescription: "Informazioni per un acquisto futuro. Non viene effettuato alcun ordine.", offerAddon: "Add-on offerte", customerAddon: "Add-on clienti", addonLine: "+{value} per {price} netti al mese", noPurchase: "Stripe e la fatturazione automatica non sono attivi. Questa vista non modifica piano o capacità.", cancel: "Chiudi", warningTitle: "Avvisi capacità", warningPending: "Gli avvisi in-app ed e-mail non sono ancora attivi. Ripetizione, cooldown e cessazione richiedono una decisione del Founder.", forecastPending: "La previsione a 7 giorni resta disattivata finché dati e contratto di invio non sono pronti.", payment: "Stato pagamento", unavailable: "Non disponibile",
  },
  es: {
    title: "Plan y capacidad", description: "Tu plan actual y el uso calculado por el servidor.", back: "Volver", loading: "Cargando capacidad…", error: "No se pudieron cargar el plan y la capacidad.", retry: "Reintentar", plan: "Plan actual", netMonth: "{price} netos al mes", country: "País", commercial: "Disponibilidad de PRO", locked: "Aún no disponible", released: "Disponible", offers: "Ofertas", customers: "Clientes activos", used: "{usage} de {limit} utilizados", included: "{value} incluidos en el plan", addons: "{units} unidades adicionales activas", addonCapacity: "+{value} mediante complementos", total: "Capacidad total: {value}", remaining: "Quedan {value}", window: "Periodo móvil: últimos {days} días", asOf: "Datos a: {date}", available: "Capacidad disponible", warning80: "Capacidad utilizada al menos al 80%", warning90: "Capacidad utilizada al menos al 90%", atLimit: "Límite alcanzado", overLimit: "Capacidad superada", offerAt: "Has alcanzado la capacidad de ofertas. La capacidad adicional solo cuenta tras una contratación activa.", customerAt: "Has alcanzado la capacidad de clientes. La capacidad adicional solo cuenta tras una contratación activa.", offerOver: "Usas {usage} ofertas de {limit} disponibles. Las ofertas existentes se conservan. Para activar nuevas ofertas debes volver al límite o activar capacidad adicional.", customerOver: "Usas {usage} plazas de clientes de {limit}. Los clientes, puntos y canjes existentes se conservan. Una nueva primera actividad requiere capacidad disponible.", increase: "Aumentar capacidad", drawerTitle: "Capacidad adicional", drawerDescription: "Información para una contratación posterior. No se realiza ningún pedido.", offerAddon: "Complemento de ofertas", customerAddon: "Complemento de clientes", addonLine: "+{value} por {price} netos al mes", noPurchase: "Stripe y la facturación automática no están activos. Esta vista no cambia el plan ni la capacidad.", cancel: "Cerrar", warningTitle: "Avisos de capacidad", warningPending: "Los avisos en la aplicación y por correo aún no están activos. Repetición, pausa y resolución requieren una decisión del Founder.", forecastPending: "La previsión de 7 días seguirá desactivada hasta disponer de los datos y del contrato de envío.", payment: "Estado del pago", unavailable: "No disponible",
  },
  zh: {
    title: "套餐与容量", description: "当前套餐及服务器计算的使用量。", back: "返回", loading: "正在加载容量…", error: "暂时无法加载套餐和容量。", retry: "重试", plan: "当前套餐", netMonth: "每月净价 {price}", country: "国家/地区", commercial: "PRO 可用状态", locked: "尚未开放", released: "已开放", offers: "优惠", customers: "活跃客户", used: "已使用 {usage}/{limit}", included: "套餐包含 {value}", addons: "已启用 {units} 个扩容单位", addonCapacity: "扩容增加 +{value}", total: "总容量：{value}", remaining: "剩余 {value}", window: "滚动周期：最近 {days} 天", asOf: "数据时间：{date}", available: "容量充足", warning80: "容量使用率已达 80%", warning90: "容量使用率已达 90%", atLimit: "已达到容量上限", overLimit: "已超出容量", offerAt: "当前优惠容量已满。只有扩容正式生效后才会增加容量。", customerAt: "当前客户容量已满。只有扩容正式生效后才会增加容量。", offerOver: "当前使用 {usage} 个优惠，可用上限为 {limit}。现有优惠会保留；只有恢复到上限以内或扩容生效后才能启用新优惠。", customerOver: "当前使用 {usage} 个客户名额，可用上限为 {limit}。现有客户、积分和兑换会保留；新的首次活动需要可用容量。", increase: "增加容量", drawerTitle: "额外容量", drawerDescription: "仅提供未来扩容信息，不会下单。", offerAddon: "优惠扩容", customerAddon: "客户扩容", addonLine: "+{value}，每月净价 {price}", noPurchase: "Stripe 和自动扣费尚未启用。此页面不会更改套餐或容量。", cancel: "关闭", warningTitle: "容量提醒", warningPending: "应用内和邮件提醒尚未启用。重复频率、冷却期和解除规则仍需 Founder 决策。", forecastPending: "在数据基础和完整发送合同就绪前，7 天预测保持关闭。", payment: "付款状态", unavailable: "不可用",
  },
  ko: {
    title: "요금제 및 용량", description: "현재 요금제와 서버에서 계산한 사용량입니다.", back: "뒤로", loading: "용량을 불러오는 중…", error: "요금제와 용량을 불러올 수 없습니다.", retry: "다시 시도", plan: "현재 요금제", netMonth: "월 순액 {price}", country: "국가", commercial: "PRO 제공 상태", locked: "아직 제공되지 않음", released: "제공됨", offers: "혜택", customers: "활성 고객", used: "{limit}개 중 {usage}개 사용", included: "요금제에 {value}개 포함", addons: "추가 단위 {units}개 활성", addonCapacity: "추가 용량 +{value}", total: "총용량: {value}", remaining: "{value}개 남음", window: "이동 기간: 최근 {days}일", asOf: "기준 시각: {date}", available: "용량 사용 가능", warning80: "용량을 80% 이상 사용 중", warning90: "용량을 90% 이상 사용 중", atLimit: "용량 한도 도달", overLimit: "용량 초과", offerAt: "현재 혜택 용량에 도달했습니다. 추가 용량은 구매가 활성화된 후에만 반영됩니다.", customerAt: "현재 고객 용량에 도달했습니다. 추가 용량은 구매가 활성화된 후에만 반영됩니다.", offerOver: "현재 {limit}개 한도에서 {usage}개 혜택을 사용 중입니다. 기존 혜택은 유지됩니다. 한도 이내로 돌아오거나 추가 용량이 활성화된 후 새 혜택을 활성화할 수 있습니다.", customerOver: "현재 {limit}명 한도에서 {usage}명의 고객 용량을 사용 중입니다. 기존 고객, 포인트 및 사용 내역은 유지됩니다. 새 최초 활동에는 사용 가능한 용량이 필요합니다.", increase: "용량 늘리기", drawerTitle: "추가 용량", drawerDescription: "향후 추가 구매를 위한 정보입니다. 주문은 생성되지 않습니다.", offerAddon: "혜택 추가 용량", customerAddon: "고객 추가 용량", addonLine: "+{value}, 월 순액 {price}", noPurchase: "Stripe 및 자동 결제가 활성화되지 않았습니다. 이 화면은 요금제나 용량을 변경하지 않습니다.", cancel: "닫기", warningTitle: "용량 알림", warningPending: "앱 및 이메일 알림은 아직 활성화되지 않았습니다. 반복, 쿨다운 및 해제 규칙은 Founder 결정이 필요합니다.", forecastPending: "필요한 데이터와 전체 발송 계약이 준비될 때까지 7일 예측은 비활성화됩니다.", payment: "결제 상태", unavailable: "사용 불가",
  },
});

const WARNING_UI = Object.freeze({
  de: { warningReady: "Kapazitätswarnungen sind aktiv. Die Seite selbst erzeugt keine Warnung.", noWarnings: "Aktuell gibt es keine offene Kapazitätswarnung.", warningOffer: "Angebote", warningCustomer: "Aktive Kunden", warningActual: "Tatsächlich erreicht", warningForecast: "7-Tage-Prognose", forecastLabel: "Prognose: {value}", acknowledge: "Gelesen", acknowledged: "Bestätigt", acknowledgeError: "Die Warnung konnte nicht bestätigt werden." },
  en: { warningReady: "Capacity warnings are active. Opening this page does not create a warning.", noWarnings: "There is currently no open capacity warning.", warningOffer: "Offers", warningCustomer: "Active customers", warningActual: "Actually reached", warningForecast: "7-day forecast", forecastLabel: "Forecast: {value}", acknowledge: "Mark as read", acknowledged: "Acknowledged", acknowledgeError: "The warning could not be acknowledged." },
  fr: { warningReady: "Les alertes de capacité sont actives. L’ouverture de cette page ne crée aucune alerte.", noWarnings: "Il n’y a actuellement aucune alerte de capacité ouverte.", warningOffer: "Offres", warningCustomer: "Clients actifs", warningActual: "Seuil réellement atteint", warningForecast: "Prévision à 7 jours", forecastLabel: "Prévision : {value}", acknowledge: "Marquer comme lu", acknowledged: "Confirmé", acknowledgeError: "L’alerte n’a pas pu être confirmée." },
  it: { warningReady: "Gli avvisi di capacità sono attivi. L’apertura di questa pagina non crea avvisi.", noWarnings: "Al momento non ci sono avvisi di capacità aperti.", warningOffer: "Offerte", warningCustomer: "Clienti attivi", warningActual: "Raggiunto effettivamente", warningForecast: "Previsione a 7 giorni", forecastLabel: "Previsione: {value}", acknowledge: "Segna come letto", acknowledged: "Confermato", acknowledgeError: "Impossibile confermare l’avviso." },
  es: { warningReady: "Los avisos de capacidad están activos. Abrir esta página no genera ningún aviso.", noWarnings: "Actualmente no hay ningún aviso de capacidad abierto.", warningOffer: "Ofertas", warningCustomer: "Clientes activos", warningActual: "Alcanzado realmente", warningForecast: "Previsión de 7 días", forecastLabel: "Previsión: {value}", acknowledge: "Marcar como leído", acknowledged: "Confirmado", acknowledgeError: "No se pudo confirmar el aviso." },
  zh: { warningReady: "容量提醒已启用。打开此页面不会生成提醒。", noWarnings: "当前没有未解决的容量提醒。", warningOffer: "优惠", warningCustomer: "活跃客户", warningActual: "实际已达到", warningForecast: "7 天预测", forecastLabel: "预测：{value}", acknowledge: "标记为已读", acknowledged: "已确认", acknowledgeError: "无法确认此提醒。" },
  ko: { warningReady: "용량 알림이 활성화되어 있습니다. 이 페이지를 여는 것만으로 알림이 생성되지는 않습니다.", noWarnings: "현재 열린 용량 알림이 없습니다.", warningOffer: "혜택", warningCustomer: "활성 고객", warningActual: "실제 도달", warningForecast: "7일 예상", forecastLabel: "예상: {value}", acknowledge: "읽음으로 표시", acknowledged: "확인됨", acknowledgeError: "알림을 확인 처리할 수 없습니다." },
});

export function ownerCapacityMessages(language) {
  const locale = normalizeUiLanguage(language, "de") || "de";
  return { ...MESSAGES[locale], ...WARNING_UI[locale] };
}

export function capacityMessage(template, values = {}) {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

const PAYMENT_LABELS = Object.freeze({
  de: { paid: "Bezahlt", pending: "Zahlung offen", failed: "Zahlung fehlgeschlagen", manual: "Manuell bestätigt", not_required: "Keine Zahlung erforderlich" },
  en: { paid: "Paid", pending: "Payment pending", failed: "Payment failed", manual: "Confirmed manually", not_required: "No payment required" },
  fr: { paid: "Payé", pending: "Paiement en attente", failed: "Échec du paiement", manual: "Confirmé manuellement", not_required: "Aucun paiement requis" },
  it: { paid: "Pagato", pending: "Pagamento in sospeso", failed: "Pagamento non riuscito", manual: "Confermato manualmente", not_required: "Nessun pagamento richiesto" },
  es: { paid: "Pagado", pending: "Pago pendiente", failed: "Pago fallido", manual: "Confirmado manualmente", not_required: "No se requiere pago" },
  zh: { paid: "已付款", pending: "付款待处理", failed: "付款失败", manual: "已人工确认", not_required: "无需付款" },
  ko: { paid: "결제 완료", pending: "결제 대기", failed: "결제 실패", manual: "수동 확인", not_required: "결제 불필요" },
});

export function ownerCapacityPaymentLabel(language, status, fallback) {
  const locale = normalizeUiLanguage(language, "de") || "de";
  return PAYMENT_LABELS[locale][status] ?? fallback;
}
